### ISSUE TITLE
不能创建中文名称角色

### ISSUE THREAD

**Issue by ckchong992** [rAthenaCN/rAthenaCN#1]
大家好！
我在使用中发现不能创建中文名称角色，能帮忙看下原因吗？
感谢您的付出！

**Comment by rAthenaCN** [comment]
您好！
您提出问题已修正
![01](https://cloud.githubusercontent.com/assets/19231012/16205030/500b55d6-3754-11e6-9663-f7b60f7f0d31.jpg)
