### ISSUE TITLE
城内重置助手，重置技能点无效

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#2]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 
三转
* **问题说明**: 
 
  * 发生的错误: 
  城内重置助手：重置技能点无效
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
经过测试，并没有发现有任何的重置失效，是否能更清楚地说明一下情况？
