### ISSUE TITLE
属性界面属性翻译错位

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#3]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 属性界面，属性翻译错位
![9 ihmrqdt3 j bht8gr69](https://cloud.githubusercontent.com/assets/28803997/26275919/6e94a7d6-3d9e-11e7-90ef-f0f319972a0f.jpg)
![9 ihmrqdt3 j bht8gr69](https://cloud.githubusercontent.com/assets/28803997/26275922/7ac7eb62-3d9e-11e7-9f66-76ee245a30ad.jpg)

  * 发生的错误: 
  
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
嗯，确实有一点位置偏差，以后修正吧，感觉应该属于补丁的问题，并不是服务端的问题。
