### ISSUE TITLE
新种族错误 新种族创建人物没引导，没任务，没怪，空图

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#4]
![k4pk ly llz c0d i7fqp](https://cloud.githubusercontent.com/assets/28803997/26275938/dc00b864-3d9e-11e7-980f-872ab96ace93.jpg)

* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 
  * 发生的错误: 
  
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
![2](https://user-images.githubusercontent.com/19231012/39094627-fa7a3e08-4664-11e8-9a4b-71a161d944b2.png)
我已经添加了这些在 npc\re\custom\lasagna 文件夹内，不过它们是英文的，并没有汉化。
