### ISSUE TITLE
活动怪缺少贴图（一只叫请不要碰我的怪）

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#5]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 
  * 发生的错误: 
  
![u 4v ntypqh97 og b00gs7](https://cloud.githubusercontent.com/assets/28803997/26275947/2228113e-3d9f-11e7-93e7-45da741a1a98.jpg)

  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
这个是一个活动的宝箱，开始的时候会提示在哪个地图会出现，打开它会有东西掉落。
目前经过测试是正常的显示，无错误。
