### ISSUE TITLE
技能点bug

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#6]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 技能点加减页面减少技能点，无法退回未使用点数。且减少后无法点确定和重置(小窗模式的技能页面）
部分玩家还说在缩小的技能页面点滴技能提升图也没反应。
![n zi ggh a3kg8 o bgg](https://cloud.githubusercontent.com/assets/28803997/26276074/7bf2d8a4-3da2-11e7-9591-1e27d39254c1.png)

![4 fry621sl_ mrhu bjkv7e](https://cloud.githubusercontent.com/assets/28803997/26276058/e86f65b6-3da1-11e7-8f9b-24ee19b85d88.jpg)
![o c5quo 7p 80 x scd](https://cloud.githubusercontent.com/assets/28803997/26276059/ec033a5e-3da1-11e7-8261-79d233946bf6.png)

  * 发生的错误: 
  
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
你好，经过测试技能栏加点正常，你提出的这个问题貌似是不知道怎么正确使用技能栏导致的。
