### ISSUE TITLE
猫村鲜虾商出售物品差一个猫薄荷

### ISSUE THREAD

**Issue by iapcrazy** [rAthenaCN/rAthenaCN#7]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 
![roab7 u 6 8ga 7q0 u6b](https://cloud.githubusercontent.com/assets/28803997/26319715/a94c7da8-3f52-11e7-9451-e56ce3461fc5.jpg)
![5t6_v loegj75dzi91sixyh](https://cloud.githubusercontent.com/assets/28803997/26319718/adecb3c8-3f52-11e7-93b5-a254dd563936.jpg)

  * 发生的错误: 
  
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
11602 貓薄荷果實

比獼猴桃更小的果實,
---------------------------
可恢復少量的 HP.
---------------------------
喵族技能使用後也會消耗.
---------------------------
重量 : 0.1
