### ISSUE TITLE
剑士村上面魔法学院2层地图错误

### ISSUE THREAD

**Issue by lyc4206** [rAthenaCN/rAthenaCN#9]
* **rAthenaCN Hash**: 

* **客户端日期**: 

* **服务端模式**: 

* **问题说明**: 
 
  * 发生的错误: 
  
  * 期望的修正: 
  
  * 错误如何重现: 
  
  * 官方信息: 
  
* **可能是正确的修正建议**:

**Comment by rAthenaCN** [comment]
![1](https://user-images.githubusercontent.com/19231012/39094858-2b22c49a-4669-11e8-9fc0-e2492cf3b2ae.png)
感谢你的反馈，这个问题已经被修正在配套的完整客户端内（https://github.com/rAthenaCN/ROClientFullCN），谢谢！
